import unittest
import json
from unittest.mock import patch, mock_open
from cerne.managers.javascript import NodeManager


class TestNodeManager(unittest.TestCase):

    def setUp(self):
        self.manager = NodeManager()

    @patch("os.path.exists")
    def test_parse_npm_package_lock(self, mock_exists):
        mock_exists.side_effect = lambda f: f == "package-lock.json"

        mock_json = {
            "name": "project-npm",
            "version": "1.0.0",
            "dependencies": {
                "express": {
                    "version": "4.17.1",
                    "dependencies": {
                        "debug": {"version": "2.6.9"}
                    }
                }
            }
        }

        with patch("builtins.open", mock_open()), \
                patch("json.load", return_value=mock_json):
            root, versions = self.manager.get_dependencies()

        self.assertEqual(root.name, "project-npm")

        express_node = root.children[0]
        self.assertEqual(express_node.name, "express")
        self.assertEqual(express_node.version, "4.17.1")

        self.assertEqual(express_node.children[0].name, "debug")
        self.assertEqual(versions["debug"], "2.6.9")

    @patch("os.path.exists")
    def test_parse_yarn_lock(self, mock_exists):

        mock_exists.side_effect = lambda f: f == "yarn.lock"

        pkg_json_content = json.dumps({
            "name": "project-yarn",
            "dependencies": {"react": "^16.8.0"}
        })

        yarn_lock_content = """
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
react@^16.8.0:
  version "16.14.0"
  resolved "https://registry.yarnpkg.com/react..."
  dependencies:
    loose-envify "^1.1.0"

loose-envify@^1.1.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/loose-envify..."
  dependencies:
    js-tokens "^3.0.0"
"""

        def open_side_effect(filename, *args, **kwargs):
            if "package.json" in filename:
                return mock_open(read_data=pkg_json_content).return_value
            if "yarn.lock" in filename:
                return mock_open(read_data=yarn_lock_content).return_value
            raise FileNotFoundError(filename)

        with patch("builtins.open", side_effect=open_side_effect):
            root, versions = self.manager.get_dependencies()

        self.assertEqual(root.name, "project-yarn")
        react_node = root.children[0]
        self.assertEqual(react_node.name, "react")
        self.assertEqual(react_node.version, "16.14.0")
        self.assertEqual(react_node.children[0].name, "loose-envify")
        self.assertEqual(react_node.children[0].version, "1.4.0")
